<h3>FuturePay Merchant Login</h3>
<div class="fm-group">
    <input id="futurepay_user_name" class="fm-input" type="text" name="futurepay_user_name" placeholder="Username">
</div>
<div class="fm-group">
   <input id="futurepay_password" class="fm-input" type="password" name="futurepay_password" placeholder="Password">
</div>
<div class="fm-group last">
    <input class="fm-btn" type="button" name="save" value="Login" onclick="FuturePayAdmin.doMerchantLogin(); return false;">
</div>
<div style='clear:both'></div>